project:
  type: website
  output-dir: _site
  preview: 
    watch-inputs: true
  resources: 
    - assets/**
    - partials/**

website:
  title: "Ryan O'Loughlin"
  description: "philosophy of science • climate models • trust without truth • uncertainty"
  site-url: https://Ryan-J-OLoughlin.github.io/
  twitter-card: true
  navbar:
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: "Talks & Collaboration"
        menu:
          - text: For Philosophers
            href: for-philosophers.qmd
          - text: For Scientists
            href: for-scientists.qmd
      - text: Teaching
        #href: teaching.qmd
        menu:
          - text: Teaching Trust without Truth
            href: teaching-instructors.qmd
          - text: Resources for Students
            href: teaching-students.qmd
      - text: "Media" 
        href: media.qmd
      - text: Contact
        href: contact.qmd
    tools:
      - icon: envelope
        href: "mailto:Ryan.Oloughlin@qc.cuny.edu"
      - icon: linkedin
        href: https://www.linkedin.com/in/ryan-o-loughlin-885256300
      - icon: file-earmark-text   # optional: direct CV download
        href: /files/Ryan_OLoughlin_CV.pdf
  page-footer:
    center: 
      - text: "© 2025 Ryan J O'Loughlin"
      #- text: "Updated: {{< meta date-modified >}}"
      - text: "CC BY 4.0"
        href: https://creativecommons.org/licenses/by/4.0/
    left:
      - icon: envelope
        #text: Email
        href: "mailto:Ryan.Oloughlin@qc.cuny.edu"
      - icon: google
        #text: Scholar
        href: https://scholar.google.com/citations?user=FVgAseQAAAAJ&hl=en
      - icon: mortarboard 
        text: PhilPeople  
        href: https://philpeople.org/profiles/ryan-o-loughlin
      - icon: orcid
        text: ORCID
        href: https://orcid.org/0000-0002-9106-1460
      - icon: github
        #text: GitHub
        href: https://github.com/Ryan-J-OLoughlin/
      - icon: linkedin
        #text: LinkedIn
        href: https://www.linkedin.com/in/ryan-o-loughlin-885256300/
    right:
      - text: "Back to top ↑"
        href: "#"
      - text: "Built by DL with 🩶"
        href: https://github.com/dan-li-o
  search: true
  repo-url: https://github.com/Ryan-J-OLoughlin/Ryan-J-OLoughlin.github.io
  repo-actions: [edit, issue]

format:
  html:
    page-layout: article
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    include-in-header:
      - partials/perf-head.html
    include-after-body:
      - partials/game-modal.html
      - partials/perf-after.html
      - partials/scroll-reveal.html
    toc: true
    toc-location: right
    page-navigation: true
    smooth-scroll: true
    open-graph:
      image: assets/og-card.jpeg
      image-alt: "Ryan O'Loughlin — Philosophy of Science (climate models, uncertainty)"
    twitter-card:
      image: assets/og-card.jpeg
      card: summary_large_image
